name: the_savings_game
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - libffi=3.4.2
  - libsqlite=3.45.3
  - libzlib=1.3.1
  - openssl=3.3.0
  - pip=24.0
  - python=3.10.14
  - python-dotenv=1.0.1
  - setuptools=70.0.0
  - tk=8.6.13
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.38.33135
  - vs2015_runtime=14.38.33135
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
    - aiofiles==0.6.0
    - click==7.1.2
    - h11==0.14.0
    - itsdangerous==1.1.0
    - markupsafe==1.1.1
    - otree==5.10.4
    - python-multipart==0.0.5
    - six==1.16.0
    - sqlalchemy==1.3.22
    - starlette==0.14.1
    - uvicorn==0.13.4
    - websockets==10.1
    - wtforms==2.3.3
    - wtforms-sqlalchemy==0.2
prefix: C:\Users\nlawrenc\anaconda3\envs\the_savings_game
